// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKpIx2fCMtBPlPfHmiSD2t-iG541tc89w',
    appId: '1:663648290389:web:395eb8ab753d41c29f36dc',
    messagingSenderId: '663648290389',
    projectId: 'fruits-hub-f76ef',
    authDomain: 'fruits-hub-f76ef.firebaseapp.com',
    storageBucket: 'fruits-hub-f76ef.firebasestorage.app',
    measurementId: 'G-8D85DPXFQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZXf1BI-5zdhD979xU3FYG8mwQkhC3GPo',
    appId: '1:663648290389:android:2e84d65187ceb0a39f36dc',
    messagingSenderId: '663648290389',
    projectId: 'fruits-hub-f76ef',
    storageBucket: 'fruits-hub-f76ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBydJ1d1UWvSfSUp6KhXMIe5Q77psQ72ME',
    appId: '1:663648290389:ios:7a92603539d30e479f36dc',
    messagingSenderId: '663648290389',
    projectId: 'fruits-hub-f76ef',
    storageBucket: 'fruits-hub-f76ef.firebasestorage.app',
    androidClientId: '663648290389-vnu9hl5rb3ftstalain0plqdki6lkkmm.apps.googleusercontent.com',
    iosClientId: '663648290389-k1j2q569i769v0sv4kr71pesll5ca0eg.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBydJ1d1UWvSfSUp6KhXMIe5Q77psQ72ME',
    appId: '1:663648290389:ios:7a92603539d30e479f36dc',
    messagingSenderId: '663648290389',
    projectId: 'fruits-hub-f76ef',
    storageBucket: 'fruits-hub-f76ef.firebasestorage.app',
    androidClientId: '663648290389-vnu9hl5rb3ftstalain0plqdki6lkkmm.apps.googleusercontent.com',
    iosClientId: '663648290389-k1j2q569i769v0sv4kr71pesll5ca0eg.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKpIx2fCMtBPlPfHmiSD2t-iG541tc89w',
    appId: '1:663648290389:web:b36b29ad1155ed9c9f36dc',
    messagingSenderId: '663648290389',
    projectId: 'fruits-hub-f76ef',
    authDomain: 'fruits-hub-f76ef.firebaseapp.com',
    storageBucket: 'fruits-hub-f76ef.firebasestorage.app',
    measurementId: 'G-M1MWKJXZM2',
  );
}
